# wrangler.toml
name = "playtested"
compatibility_date = "2025-08-08"
pages_build_output_dir = "dist"
compatibility_flags = ["nodejs_compat"]


[[kv_namespaces]]
binding = "SUMMARY_CACHE"
id = "485ded38c4c945a59d4aced99acd1a8e" # Production KV ID

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTOR_DB"
index_name = "playbook-local"