logo_url: "/images/logo01.avif"

backend:
  name: github
  repo: lyndon025/playtested
  branch: main
  base_url: https://www.playtested.net
  auth_endpoint: auth
  use_graphql: false
  open_authoring: true

site_url: https://www.playtested.net

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

editor:
  preview: false      

collections:

  - name: "submissions"
    label: "User Submissions"
    folder: "src/content/submissions"
    create: true
    slug: "{{fields.game}}"
    preview_path: "article/{{slug}}"
    sortable_fields: ["draft", "commit_date", "pubDate", "title"]
    sort: "draft:desc, commit_date:desc"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Review Title | Game Name Review (e.g. Best Game Ever | Half-Life Review)"  }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", hint: "You can backdate this to older dates (From when you wrote the review or played the game)"  }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Description", name: "description", widget: "text", hint: "Write a short one paragraph summary or copy paste the first/second paragraph of your review" }

      # Category: dropdown (required)
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["review", "tech", "write-up"]
        required: true

              # Tags: multiple select, at least 1, allow custom values
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["PC", "Console", "Mobile"]
        allow_add: true
        required: true

      - { label: "Featured on Home", name: "featured", widget: "boolean", default: false, required: false }

      # Thumbnail: required image
      - { label: "Thumbnail", name: "thumb", widget: "image", required: true }

      - { label: "Author", name: "author", widget: "string", default: "lyndonguitar" }
      - { label: "Game", name: "game", widget: "string", required: false }


      # Gallery: optional list of images (array of strings)
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        field: { label: "Image", name: "image", widget: "image" }
        hint: "You can add images one a time only" 
      - { label: "Score", name: "score", widget: "number", value_type: "float", min: 0, max: 10, step: 0.1, required: false, hint: "From 0 to 10 with 0.1 increments (e.g. 7.3 is okay)"  }
      - { label: "Body", name: "body", widget: "markdown", hint: "Put your actual full review here"  }

  - name: "article"
    label: "Lyndon Articles"
    folder: "src/content/article"
    create: true
    slug: "{{fields.game}}"
    preview_path: "article/{{slug}}"
    sortable_fields: ["draft", "commit_date", "pubDate", "title"]
    sort: "draft:desc, commit_date:desc"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Review Title | Game Name Review (e.g. Best Game Ever | Half-Life Review)" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", hint: "You can backdate this to older dates (From when you wrote the review or played the game)"  }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Description", name: "description", widget: "text", hint: "Write a short one paragraph summary or copy paste the first/second paragraph of your review"  }

      # Category: dropdown (required)
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["review", "tech", "write-up"]
        required: true

              # Tags: multiple select, at least 1, allow custom values
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["PC", "Console", "Mobile"]
        allow_add: true
        required: true

      - { label: "Featured on Home", name: "featured", widget: "boolean", default: false, required: false }

      # Thumbnail: required image
      - { label: "Thumbnail", name: "thumb", widget: "image", required: true }

      - { label: "Author", name: "author", widget: "string", default: "lyndonguitar" }
      - { label: "Game", name: "game", widget: "string", required: false }


      # Gallery: optional list of images (array of strings)
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        field: { label: "Image", name: "image", widget: "image" }
        hint: "You can add images one a time only" 
      - { label: "Score", name: "score", widget: "number", value_type: "float", min: 0, max: 10, step: 0.1, required: false, hint: "From 0 to 10 with 0.1 increments (e.g. 7.3 is okay)"  }
      - { label: "Body", name: "body", widget: "markdown", hint: "Put your actual full review here"  }